config/routes.rb
Rails.application.routes.draw do

  resources :screenings
  resources :applications
  resources :users_courses
  resources :courses
  resources :users
  resources :instructors, controller: 'users', type: 'Instructor'
  resources :admissions_officers, controller: 'users', type: 'Admissions_Officer'
  resources :candidates, controller: 'users', type: 'Candidate'

end

app/models/screening.rb
class Screening < ActiveRecord::Base
  belongs_to :user
  belongs_to :application
end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  before_action :set_screening, only: [:show, :edit, :update, :destroy]

  # GET /screenings
  # GET /screenings.json
  def index
    @screenings = Screening.all
  end

  # GET /screenings/1
  # GET /screenings/1.json
  def show
  end

  # GET /screenings/new
  def new
    @screening = Screening.new
  end

  # GET /screenings/1/edit
  def edit
  end

  # POST /screenings
  # POST /screenings.json
  def create
    @screening = Screening.new(screening_params)

    respond_to do |format|
      if @screening.save
        format.html { redirect_to @screening, notice: 'Screening was successfully created.' }
        format.json { render :show, status: :created, location: @screening }
      else
        format.html { render :new }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screenings/1
  # PATCH/PUT /screenings/1.json
  def update
    respond_to do |format|
      if @screening.update(screening_params)
        format.html { redirect_to @screening, notice: 'Screening was successfully updated.' }
        format.json { render :show, status: :ok, location: @screening }
      else
        format.html { render :edit }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenings/1
  # DELETE /screenings/1.json
  def destroy
    @screening.destroy
    respond_to do |format|
      format.html { redirect_to screenings_url, notice: 'Screening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screening
      @screening = Screening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screening_params
      params.require(:screening).permit(:user_id, :application_id, :type, :date, :duration, :notes, :buffer)
    end
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/views/screenings/_form.html.erb
<%= form_for(@screening) do |f| %>
  <% if @screening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screening.errors.count, "error") %> prohibited this screening from being saved:</h2>

      <ul>
      <% @screening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :application_id %><br>
    <%= f.text_field :application_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :buffer %><br>
    <%= f.text_area :buffer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screenings/edit.html.erb
<h1>Editing Screening</h1>

<%= render 'form' %>

<%= link_to 'Show', @screening %> |
<%= link_to 'Back', screenings_path %>

app/views/screenings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Screenings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Application</th>
      <th>Type</th>
      <th>Date</th>
      <th>Duration</th>
      <th>Notes</th>
      <th>Buffer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screenings.each do |screening| %>
      <tr>
        <td><%= screening.user %></td>
        <td><%= screening.application %></td>
        <td><%= screening.type %></td>
        <td><%= screening.date %></td>
        <td><%= screening.duration %></td>
        <td><%= screening.notes %></td>
        <td><%= screening.buffer %></td>
        <td><%= link_to 'Show', screening %></td>
        <td><%= link_to 'Edit', edit_screening_path(screening) %></td>
        <td><%= link_to 'Destroy', screening, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screening', new_screening_path %>

app/views/screenings/new.html.erb
<h1>New Screening</h1>

<%= render 'form' %>

<%= link_to 'Back', screenings_path %>

app/views/screenings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @screening.user %>
</p>

<p>
  <strong>Application:</strong>
  <%= @screening.application %>
</p>

<p>
  <strong>Type:</strong>
  <%= @screening.type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @screening.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @screening.duration %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @screening.notes %>
</p>

<p>
  <strong>Buffer:</strong>
  <%= @screening.buffer %>
</p>

<%= link_to 'Edit', edit_screening_path(@screening) %> |
<%= link_to 'Back', screenings_path %>