config/routes.rb
Rails.application.routes.draw do

  resources :screenings
  resources :applications
  resources :users_courses
  resources :courses
  resources :users
  resources :instructors, controller: 'users', type: 'Instructor'
  resources :admissions_officers, controller: 'users', type: 'Admissions_Officer'
  resources :candidates, controller: 'users', type: 'Candidate'

end

app/controllers/users_courses_controller.rb
class UsersCoursesController < ApplicationController
  before_action :set_users_course, only: [:show, :edit, :update, :destroy]

  # GET /users_courses
  # GET /users_courses.json
  def index
    @users_courses = UsersCourse.all
  end

  # GET /users_courses/1
  # GET /users_courses/1.json
  def show
  end

  # GET /users_courses/new
  def new
    @users_course = UsersCourse.new
  end

  # GET /users_courses/1/edit
  def edit
  end

  # POST /users_courses
  # POST /users_courses.json
  def create
    @users_course = UsersCourse.new(users_course_params)

    respond_to do |format|
      if @users_course.save
        format.html { redirect_to @users_course, notice: 'Users course was successfully created.' }
        format.json { render :show, status: :created, location: @users_course }
      else
        format.html { render :new }
        format.json { render json: @users_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_courses/1
  # PATCH/PUT /users_courses/1.json
  def update
    respond_to do |format|
      if @users_course.update(users_course_params)
        format.html { redirect_to @users_course, notice: 'Users course was successfully updated.' }
        format.json { render :show, status: :ok, location: @users_course }
      else
        format.html { render :edit }
        format.json { render json: @users_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_courses/1
  # DELETE /users_courses/1.json
  def destroy
    @users_course.destroy
    respond_to do |format|
      format.html { redirect_to users_courses_url, notice: 'Users course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_course
      @users_course = UsersCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_course_params
      params.require(:users_course).permit(:user_id, :course_id, :buffer)
    end
end

app/helpers/users_courses_helper.rb
module UsersCoursesHelper
end

app/views/users_courses/_form.html.erb
<%= form_for(@users_course) do |f| %>
  <% if @users_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_course.errors.count, "error") %> prohibited this users_course from being saved:</h2>

      <ul>
      <% @users_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :buffer %><br>
    <%= f.text_field :buffer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_courses/edit.html.erb
<h1>Editing Users Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_course %> |
<%= link_to 'Back', users_courses_path %>

app/views/users_courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users Courses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Course</th>
      <th>Buffer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_courses.each do |users_course| %>
      <tr>
        <td><%= users_course.user %></td>
        <td><%= users_course.course %></td>
        <td><%= users_course.buffer %></td>
        <td><%= link_to 'Show', users_course %></td>
        <td><%= link_to 'Edit', edit_users_course_path(users_course) %></td>
        <td><%= link_to 'Destroy', users_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users course', new_users_course_path %>

app/views/users_courses/new.html.erb
<h1>New Users Course</h1>

<%= render 'form' %>

<%= link_to 'Back', users_courses_path %>

app/views/users_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @users_course.user %>
</p>

<p>
  <strong>Course:</strong>
  <%= @users_course.course %>
</p>

<p>
  <strong>Buffer:</strong>
  <%= @users_course.buffer %>
</p>

<%= link_to 'Edit', edit_users_course_path(@users_course) %> |
<%= link_to 'Back', users_courses_path %>