config/routes.rb
Rails.application.routes.draw do

  resources :screenings
  resources :applications
  resources :users_courses
  resources :courses
  resources :users
  resources :instructors, controller: 'users', type: 'Instructor'
  resources :admissions_officers, controller: 'users', type: 'Admissions_Officer'
  resources :candidates, controller: 'users', type: 'Candidate'

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :screenings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
    @users = User.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    # @application = Application.new(application_params)
    @application = Application.create(user_id: params[:user_id], course_id: params[:course_id], resume: params[:resume], status: params[:status], stage: params[:stage], notes: params[:notes], education: params[:education], experience: params[:experience], skils: params[:skils], motive: params[:motive], hear: params[:hear], additional: params[:additional])
    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:user_id, :course_id, :resume, :status, :stage, :notes, :education, :experience, :skils, :motive, :hear, :additional, :buffer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :resume %><br>
    <%= f.text_field :resume %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.text_field :stage %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_area :education %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_area :experience %>
  </div>
  <div class="field">
    <%= f.label :skils %><br>
    <%= f.text_area :skils %>
  </div>
  <div class="field">
    <%= f.label :motive %><br>
    <%= f.text_area :motive %>
  </div>
  <div class="field">
    <%= f.label :hear %><br>
    <%= f.text_area :hear %>
  </div>
  <div class="field">
    <%= f.label :additional %><br>
    <%= f.text_area :additional %>
  </div>
  <div class="field">
    <%= f.label :buffer %><br>
    <%= f.text_area :buffer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<%= react_component 'AppsIndex', {users: @users, applications: @applications} %></div>

app/views/applications/new.html.erb
<h1>New Application</h1>


<%= react_component 'NewApp', {app: @application} %></div>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @application.user %>
</p>

<p>
  <strong>Course:</strong>
  <%= @application.course %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @application.resume %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application.status %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @application.stage %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @application.notes %>
</p>

<p>
  <strong>Education:</strong>
  <%= @application.education %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @application.experience %>
</p>

<p>
  <strong>Skils:</strong>
  <%= @application.skils %>
</p>

<p>
  <strong>Motive:</strong>
  <%= @application.motive %>
</p>

<p>
  <strong>Hear:</strong>
  <%= @application.hear %>
</p>

<p>
  <strong>Additional:</strong>
  <%= @application.additional %>
</p>

<p>
  <strong>Buffer:</strong>
  <%= @application.buffer %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>